#!/usr/bin/bash
arg1=$1
arg2=$2

echo "Using standard C++ 20"

if [ "$arg2" == "clean" ]; then
    echo "Cleaning before build"
    rm -rf build
    cmake --preset=Debug
fi

if [ "$arg1" == "tests" ]; then
    echo "Running tests"
    cmake --build build --preset=Debug --target tests && ./build/Debug/tests/tests -v2
elif [ "$arg1" == "main" ]; then
    echo "Running main"
    cmake --build build --preset=Debug --target XCursorMorph && ./build/Debug/XCursorMorph
elif [ "$arg1" == "build" ]; then
    echo "Building"
    cmake --build build --preset=Debug
else
    echo "Invalid argument"
fi
